---
title: "Predictor sets"
output: github_document
---

```{r}
devtools::wd()
analyzed_data <- readRDS("not_public/analyzed_data.rds")
```


Current offences
```{r}
offence_variables <-
  c("o_traffic", "o_assault", "o_homicide", "o_sexual", "o_otherPerson",
    "o_robbery", "o_theft", "o_autoTheft", "o_otherProperty",
    "o_whitecollar", "o_narcotic", "o_damage", "o_againstOfficer",
    "o_weapon", "o_other")


```

Static predictors, including current offences.
```{r}
predset_static <-
  c("ageFirstSentence_mr", "ageFirst_missing", "ageAtRelease",
    "ps_escapeHistory", "ps_prisonTerms_mr", "ps_comServiceTerms_mr",
    "ps_remandTerms_mr", "ps_defaultTerms_mr", "ps_info_missing",
    offence_variables)
```


RITA-items. The dynamic risk factors in this study.
```{r}
(predset_rita <-
    stringr::str_subset(names(analyzed_data), "^i_"))

```


Variables related to sentence term
```{r}
predset_term <- c("openPrison", "conditionalReleaseOutcome",
               "crimeDuringSentence", "supervisedParole")
```

Save and make available in package
```{r}
devtools::use_data(predset_static)
devtools::use_data(predset_rita)
devtools::use_data(predset_term)
```

