---
title: "Training logistic regression models"
author: "Benny Salo"
date: "2018-04-12"
output: github_document
---

Training set is defined in 01_analyzed_data.Rmd
```{r message=FALSE, warning=FALSE}
devtools::wd()
training_set <- readRDS("not_public/training_set.rds")
```

Get the part of model_grid that are logistic regression models.
```{r}
library(dplyr)
glm_grid <- model_grid %>% filter(model_type == "Logistic regression")
```

Train each model (rows) in the grid according to specifications in the grid. Place results in the train_result columns (previously intitiated).

(Record how long it takes to run.)
```{r}

start <- Sys.time()

glm_grid$train_result <- purrr::map2(
  .x = glm_grid$rhs,
  .y = glm_grid$lhs,
  .f = ~ caret::train(
    x         = training_set[.x],
    y         = training_set[[.y]],
    method    = "glm",
    family    = "binomial",
    metric    = "ROC",
    trControl = ctrl_fun_training
    )
  )

time_to_run <- Sys.time() - start
time_to_run

```
Save the results as a named list.

```{r}
trained_mods_glm <- glm_grid$train_result
names(trained_mods_glm) <- glm_grid$model_name
```


```{r message=FALSE, warning=FALSE}
devtools::wd()
saveRDS(trained_mods_glm, "not_public/trained_mods_glm.rds")
```

