---
title: "Table 2 - Pseudo R2"
date: "`r Sys.Date()`"
output: github_document
---

```{r}
devtools::load_all(".")
library(dplyr)
library(caret)
```


```{r}
# Functions from dplyr used (select, mutate, group_by, summarise)
McF_tbl_cv <-
model_perfs_training_set1000$values %>% 
  select(Resample, ends_with(match = "McF_R2")) %>% 
  tidyr::gather(-Resample, key = model, value = McF_R2) %>%
  # mutate(logit_R2 = log(McF_R2 / (1-McF_R2))) %>% 
  group_by(model) %>% 
  summarise(median_McF_R2 = median(McF_R2),
            ci95_LL_R2    = quantile(McF_R2, probs = 0.025),
            ci95_UL_R2   = quantile(McF_R2, probs = 0.975),
            p_one_side   = mean(McF_R2 < 0)) %>% 
  # # Remove the column `mean_logit` 
  # select(-mean_logit) %>% 
  # Remove ~ROC from the end of the model name
  mutate(model = stringr::str_replace(model, pattern = "~McF_R2", ""))

```

```{r}
model_desc <- model_grid[c("model_name", "outcome", 
                           "predictors", "model_type", "analysis")]


table_2 <- full_join(model_desc, McF_tbl_cv, by = c("model_name" = "model")) %>% 
  filter(model_type == "Elastic net" | analysis == "Dimension analyses") %>% 
  arrange(outcome, desc(analysis), predictors) %>% 
  select(-model_name, -analysis, -model_type) %>% 
  mutate_at(.vars = vars(3:5), round, 3)
```



```{r}
knitr::kable(table_2)
```



```{r}
test_metrics <- c("logLoss", "d_AUC", "McF_R2") 


my_diff <- function(model_vector) {
  diff(model_perfs_training_set1000, 
     models = model_vector,
     metric = test_metrics,
     adjustment = "none")
}


qet_quantiles_test <- 
  function(model_vector, metric = "logLoss", 
           sided = "two", Bonf_cor_n = 1, alpha = 0.05) {

  lim <- alpha / Bonf_cor_n
  if(sided == "two") {
    prob_lims <- c(lim/2, 1 - lim/2)
  } else if (sided == "lower") {
    prob_lims <- lim 
  } else if (sided == "upper") {
    prob_lims <- 1- lim 
  }  else {
    print('argument sided should be "two", "lower", or "upper"')
  }
  
  my_diff.resamples <- my_diff(c(model_vector))
  analyzed_difs     <- my_diff.resamples$difs[[metric]]
  
  comp     <- c("comparison" = paste(my_diff.resamples$models[1], " - ",
                                     my_diff.resamples$models[2]))
  metric   <- c("metric" = metric)

  median_dif <- c("median_dif" = round(median(analyzed_difs), 4))
  
  CI       <- round(quantile(analyzed_difs, probs = prob_lims), 3)

  # Uncorrected p
  p_1      <- min(mean(analyzed_difs > 0), mean(analyzed_difs < 0))

  p_2      <- p_1 + mean(analyzed_difs > (2 * abs(median_dif)))

  out <- c(metric, median_dif, CI, "p(1s_uncor.)" = p_1, "p(2s_uncor.)" = p_2)
  print(comp)
  print(out)
}
```




