---
title: "Calibration 2"
output: html_notebook
date: 2017-12-05
---

```{r}
library(tidyverse)
library(stringr)
library(broom)
library(caret)
library(ggthemes)
```






Put outcomes and predictions in same data frame




```{r}
make_quintiles <- function(x) {
  quint_breaks <- (quantile(x, probs = seq(0, 1, 0.2)))
  quintiles    <- cut(x, 
                      breaks = quint_breaks, 
                      include.lowest = TRUE, 
                      labels = FALSE)
  quintiles
}





```

Put each prediction into a bin (1 to 5) based on quitile
```{r}

bins <-
  predictions %>%
  mutate_all(.funs = make_quintiles)

names(bins) <- paste(names(bins),".bin", sep = "")


```

Put eveything in a single data frame: 
- the predictions, 
- corresponding quintile bin, and 
- the two outcomes

```{r}
calibr_data <- data.frame(predictions, bins, 
                          reoffenceThisTerm = test_set$reoffenceThisTerm, 
                          newO_violent = test_set$newO_violent)

```

```{r}
# predictions %>% 
#   gather(key = "model", value = "predictions") %>% 
#   nest(-model)
```

```{r}
# bins_list <-
# bins %>% 
#   gather(key = "model", value = "bin") %>% 
#   nest(-model)
```
Write a function to calculate the rate of an outcome per bin.

```{r}
get_prop_per_bin <- function(dframe = calibr_data, probs, bin, outcome) {
  bin     <- enquo(bin)
  outcome <- enquo(outcome)
  probs   <- enquo(probs)
  
  var_name <- names(dframe %>% select(!!probs))

  bin_props <-
  dframe %>% 
    select(!!probs, !!bin, !!outcome) %>% 
    group_by(!!bin) %>% 
    summarise(n = n(), 
              obs = sum(as.numeric(!!outcome) == 2),
              prop = obs/n * 100,
              mean_rate = mean(!!probs)*100) %>% 
    select(-n, -obs)
  
  names(bin_props) <- c(paste(var_name, ".bin", sep = ""),
                      paste(var_name, ".rec_rate", sep = ""),
                      paste(var_name, ".m_pred", sep = ""))
  bin_props
  # names(bin_props)[2] <- paste("p.", names(bin_props[1]))
  # 
  # 
  # out <- data.frame(a = as.numeric(c(10, 30, 50, 70, 90)))
  # names(out) <- names(bin_props)[1]
  # 
  # left_join(out, bin_props)

}

get_prop_per_bin(calibr_data, G_staticp_glm, G_staticp_glm.bin, reoffenceThisTerm)


```


```{r}

calibr_data <-
bind_cols(
  get_prop_per_bin(calibr_data, items_V_rf,       items_V_rf.bin , newO_violent),
  get_prop_per_bin(calibr_data, facto_V_rf,       facto_V_rf.bin ,newO_violent),
  get_prop_per_bin(calibr_data, stati_V_rf,       stati_V_rf.bin ,newO_violent),
  get_prop_per_bin(calibr_data, stati_items_V_rf, stati_items_V_rf.bin ,newO_violent),
  get_prop_per_bin(calibr_data, stati_facto_V_rf, stati_facto_V_rf.bin ,newO_violent),
  get_prop_per_bin(calibr_data, full_items_V_rf,  full_items_V_rf.bin ,newO_violent),
  get_prop_per_bin(calibr_data, full_facto_V_rf,  full_facto_V_rf.bin ,newO_violent),
  get_prop_per_bin(calibr_data, items_G_rf,       items_G_rf.bin ,reoffenceThisTerm),
  get_prop_per_bin(calibr_data, facto_G_rf,       facto_G_rf.bin ,reoffenceThisTerm),
  get_prop_per_bin(calibr_data, stati_G_rf,       stati_G_rf.bin ,reoffenceThisTerm),
  get_prop_per_bin(calibr_data, stati_items_G_rf, stati_items_G_rf.bin ,reoffenceThisTerm),
  get_prop_per_bin(calibr_data, stati_facto_G_rf, stati_facto_G_rf.bin ,reoffenceThisTerm),
  get_prop_per_bin(calibr_data, full_items_G_rf,  full_items_G_rf.bin , reoffenceThisTerm),
  get_prop_per_bin(calibr_data, full_facto_G_rf,  full_facto_G_rf.bin , reoffenceThisTerm),
  get_prop_per_bin(calibr_data, items_V_glm,      items_V_glm.bin ,newO_violent),
  get_prop_per_bin(calibr_data, facto_V_glm,      facto_V_glm.bin ,newO_violent),
  get_prop_per_bin(calibr_data, stati_V_glm,      stati_V_glm.bin ,newO_violent),
  get_prop_per_bin(calibr_data, stati_items_V_glm, stati_items_V_glm.bin ,newO_violent),
  get_prop_per_bin(calibr_data, stati_facto_V_glm, stati_facto_V_glm.bin ,newO_violent),
  get_prop_per_bin(calibr_data, full_items_V_glm, full_items_V_glm.bin ,newO_violent),
  get_prop_per_bin(calibr_data, full_facto_V_glm, full_facto_V_glm.bin ,newO_violent),
  get_prop_per_bin(calibr_data, items_G_glm,      items_G_glm.bin ,reoffenceThisTerm),
  get_prop_per_bin(calibr_data, facto_G_glm,      facto_G_glm.bin ,reoffenceThisTerm),
  get_prop_per_bin(calibr_data, stati_G_glm,      stati_G_glm.bin ,reoffenceThisTerm),
  get_prop_per_bin(calibr_data, stati_items_G_glm, stati_items_G_glm.bin ,reoffenceThisTerm),
  get_prop_per_bin(calibr_data, stati_facto_G_glm, stati_facto_G_glm.bin ,reoffenceThisTerm),
  get_prop_per_bin(calibr_data, full_items_G_glm, full_items_G_glm.bin ,reoffenceThisTerm),
  get_prop_per_bin(calibr_data, full_facto_G_glm, full_facto_G_glm.bin ,reoffenceThisTerm)
)





```

```{r}
m_preds <- calibr_data %>%  select(ends_with("m_pred")) %>% 
  gather(key = "model", value = "m_preds") %>% 
  mutate(model = str_replace(model, ".m_pred", ""))
     
rec_rates <- calibr_data %>%  select(ends_with("rec_rate"))  %>% 
gather(key = "model", value = "rec_rate") %>% 
  mutate(model = str_replace(model, ".rec_rate", ""))

plot_data <- bind_cols(m_preds, rec_rates) %>% 
  select(-model1)
```

```{r}
# plot_data <-
# plot_data %>% 
#   mutate(r_type    = as.factor(ifelse(str_detect(plot_data$model, "_V_"), "violent", "general")),
#          algorithm = as.factor(ifelse(str_detect(plot_data$model, "_rf"), "rf", "glm")),
#          predictors = model)
# 
# plot_data$predictors <-
# str_replace(plot_data$predictors, pattern = "_V_.*", replacement = "") %>% 
#   str_replace("_G_.*$", "") %>% 
#   str_replace("^p..", "")
# 
# plot_data <-
#   mutate(plot_data, predictors = as.factor(predictors))
#   

```

```{r}
plot_data <-
plot_data %>% 
  mutate(newO_type = ifelse(str_detect(model, pattern = "_V_"), "Violent recidivism", 
                            "General recidivism"),
         model_type = ifelse(str_detect(model, pattern = "_rf"), "Random forest", 
                             "Elastic net"),
         Predictors = ifelse(str_detect(model, "^facto_"), "Dynamic factors",
                       ifelse(str_detect(model, "^items"), "Dynamic items",
                       ifelse(str_detect(model, "^stati_facto_"), 
                              "Static variables and dynamic factors",
                       ifelse(str_detect(model, "^stati_items_"), 
                              "Static and dynamic items",
                       ifelse(str_detect(model, "^full_items_"), "All predictors",
                       ifelse(str_detect(model, "^full_facto_"), "All with factors",       
                              "Static items")))))))
                     


plot_data$Predictors <- factor(plot_data$Predictors, levels = 
                                 c("All predictors", "Static and dynamic items", 
                                   "Static items",  "Dynamic items",
                                   "All with factors", "Static variables and dynamic factors",
                                   "Dynamic factors"))
```

```{r fig.width=6.5}
calibration_plot <-
plot_data %>% 
  filter(Predictors %in% c("Dynamic items", "Static items", 
                           "Static and dynamic items", "All predictors")) %>% 
ggplot(aes(x = m_preds, y = rec_rate, group = Predictors)) +
  geom_line(aes(lty = Predictors), alpha = 0.5) + 
  geom_point(aes(shape = Predictors)) +
  geom_abline() +
  scale_shape_manual(values = c(16, 4, 1, 17)) +
  scale_x_continuous(limits = c(0,100)) + 
  facet_grid(newO_type ~ model_type) + 
  ylab("Recidivism rate in quintile") +
  xlab("Average estimated probability of recidivism in quintile") + 
  theme_tufte()


  calibration_plot


```

```{r}
saveRDS(calibration_plot, "C:/Users/benny_000/Dropbox/AAAKTUELLT/Manuskript 2/calibration_plot.rds")
```



