---
title: "Descriptive statistics"
date: "`r Sys.Date()`"
output: github_document
---

Mean (and standard deviation) or frequency (and percentage) for all predictors by reoffense category.

This is an extension of Table 1 in the manuscript displaying descriptive statistics for all variables.


```{r echo=FALSE, message=TRUE, warning=FALSE}
devtools::load_all(".")
library(dplyr)
```

```{r}
knitr::kable(descriptive_stats_preds, format = "markdown")
```

```{r echo=FALSE, message=TRUE, warning=FALSE}
knitr::kable(descriptive_stats_newO, format = "markdown")
```

```{r}
test_set_logits <- test_set_predictions
test_set_logits[4:length(test_set_logits)] <-
  purrr::map_df(test_set_logits[4:length(test_set_logits)], 
                .f = ~calc_logit_from_p(.x, offset_for_01 = 0.001)) 

test_set_logits <- select(test_set_logits, -reoffenceThisTerm, -newO_violent)

```

```{r}
test_set_logits_2 <- select(test_set_logits, -reoff_category)


  spl_by <- test_set_logits[["reoff_category"]]

  model_logits <- 
    furniture::table1(test_set_logits_2,
                      splitby = spl_by,
                      digits = 2,
                      type = c("full"),
                      test = TRUE)

    names(model_logits$Table1) <- c("Model", "No reoffence", "Non-violent reoffence",
                                    "Violent reoffence", "Test", "P-value")
  
knitr::kable(model_logits, format = "markdown")
```


