#' Variable table
#'
#' Variable names, labels, the role they play in the analyses and comments.
#' For RITA-items comments this includes the full wording of the item translated
#' from english by the study authors.
#'
#' @format A data frame with 53940 rows and 10 variables:
#' \describe{
#'   \item{Variable}{Variable name as used in R scripts}
#'   \item{Label}{Short descriptive label}
#'   \item{Role}{The role the variable plays in the analyses.
#'   Can be outcome, predictor_static, predictor_dynamic, predictor_term, or descriptive}
#'   \item{Comment}{Additional comments.}
#'   ...
#' }
#' @source variable_table.csv compiled by Benny Salo
"variable_table"

#' Discrimination of models in training set.y
#'
#' The 'values' element contains a data frame with 100 rows of the results in
#' the 10 by 10 fold cross-validation. For each model the ROC(AUC),
#' is recorded along with sensitivity and specificity for decision cutoff of 0.5.
#' That gives us 24 model x 3 measures = 72 columns. With the resample numbers
#' that is 73 columns.
#'
#' @format A list with 6 elements of class 'resamples' created by
#' 'caret::resamples'
#' @seealso caret::resamples
#'
#' @source Scripts for how the results were created are stored in /data-raw
"model_AUCs_training_set"

#' Model performances in the training set based on 1000 resamples
#'
#' This a data object of class \code{resamples} generated by
#' \code{caret::resamples} that contains the model performance of all models in
#' the training set based on 250 resamples of a 4-fold cross-validation. Model names can be looked up
#' \code{model_grid}.
#'
#' The performance metrics are:
#' - d_AUC: Cohen's d based on a naive transformation from Area Under Curve
#' - E_O_ratio
#' - logLoss
#' - McF_R2: McFadden's Pseudo R^2
#' - ROC: Area Under Curve from a receiver operating characteristic curve.
#'
#'
#' @source The data object is created in
#'   "data-raw/06_model_perfs_training_set.Rmd". See also
#'   "data-raw/00_About_data_raw.Rmd"
"model_perfs_training_set1000"

