#' Variable table
#'
#' Variable names, labels, the role they play in the analyses and comments.
#' For RITA-items comments this includes the full wording of the item translated
#' from english by the study authors.
#'
#' @format A data frame with 114 rows and 5 variables:
#' \describe{
#'   \item{Variable}{Variable name as used in R scripts}
#'   \item{Label}{Short descriptive label}
#'   \item{Role}{The role the variable plays in the analyses.
#'   Can be outcome, predictor_static, predictor_dynamic, predictor_term, or descriptive}
#'   \item{Desriptives}{The type of descriptive statistics to produce for the variable}
#'   \item{Comment}{Additional comments}
#'
#' }
#' @source variable_table.csv compiled by Benny Salo
"variable_table"



#' Model performances in the training set based on 1000 resamples
#'
#' This a data object of class \code{resamples} generated by
#' \code{caret::resamples} that contains the model performance of all models in
#' the training set based on 250 resamples of a 4-fold cross-validation. Model names can be looked up
#' \code{model_grid}.
#'
#' The performance metrics are:
#' - d_AUC: Cohen's d based on a naive transformation from Area Under Curve
#' - E_O_ratio
#' - logLoss
#' - McF_R2: McFadden's Pseudo R^2
#' - ROC: Area Under Curve from a receiver operating characteristic curve.
#'
#'
#' @source The data object is created in
#'   "data-raw/06_model_perfs_training_set.Rmd". See also
#'   "data-raw/00_About_data_raw.Rmd"
"model_perfs_training_set1000"

